-- API Providers: external partners yang akses PDAM payment via API
-- Run: mysql -u yakinyakin pedami_payment < database/migrations/20260408_api_providers.sql

CREATE TABLE IF NOT EXISTS api_providers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(50) NOT NULL UNIQUE COMMENT 'Kode unik provider (e.g. TOKPED, BUKALAPAK)',
  api_key VARCHAR(64) NOT NULL UNIQUE COMMENT 'Public API key',
  api_secret VARCHAR(128) NOT NULL COMMENT 'Secret for HMAC signature',
  status ENUM('active', 'suspended', 'inactive') NOT NULL DEFAULT 'active',
  rate_limit_per_minute INT NOT NULL DEFAULT 60 COMMENT 'Max requests per minute',
  rate_limit_per_day INT NOT NULL DEFAULT 10000 COMMENT 'Max requests per day',
  allowed_ips TEXT DEFAULT NULL COMMENT 'Comma-separated allowed IPs (NULL = allow all)',
  webhook_url VARCHAR(500) DEFAULT NULL COMMENT 'URL callback for async payment results',
  webhook_secret VARCHAR(128) DEFAULT NULL COMMENT 'HMAC secret for signing webhook payloads',
  balance DECIMAL(15,2) NOT NULL DEFAULT 0 COMMENT 'Deposit saldo provider',
  min_balance DECIMAL(15,2) NOT NULL DEFAULT 0 COMMENT 'Batas minimum saldo',
  admin_fee DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT 'Biaya admin per transaksi',
  user_id INT DEFAULT NULL COMMENT 'User yang mewakili provider ini',
  loket_id INT DEFAULT NULL COMMENT 'Loket yang mewakili provider ini',
  contact_name VARCHAR(100) DEFAULT NULL,
  contact_email VARCHAR(200) DEFAULT NULL,
  contact_phone VARCHAR(20) DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_provider_code (code),
  INDEX idx_provider_api_key (api_key),
  INDEX idx_provider_status (status),
  INDEX idx_provider_user (user_id),
  INDEX idx_provider_loket (loket_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS provider_transactions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  provider_id INT NOT NULL,
  provider_code VARCHAR(50) NOT NULL,
  provider_ref VARCHAR(100) DEFAULT NULL COMMENT 'Reference ID dari provider',
  idempotency_key VARCHAR(100) NOT NULL COMMENT 'Idempotency key dari provider',
  transaction_type ENUM('inquiry', 'payment') NOT NULL,
  cust_id VARCHAR(50) NOT NULL,
  status ENUM('PENDING', 'SUCCESS', 'FAILED') NOT NULL DEFAULT 'PENDING',
  request_payload JSON DEFAULT NULL,
  response_payload JSON DEFAULT NULL,
  amount DECIMAL(15,2) DEFAULT NULL,
  admin_fee DECIMAL(10,2) DEFAULT NULL,
  total DECIMAL(15,2) DEFAULT NULL,
  error_code VARCHAR(50) DEFAULT NULL,
  error_message TEXT DEFAULT NULL,
  transaction_code VARCHAR(100) DEFAULT NULL COMMENT 'Internal PDAM transaction code',
  ip_address VARCHAR(45) DEFAULT NULL,
  duration_ms INT DEFAULT NULL COMMENT 'Processing time in milliseconds',
  webhook_status ENUM('pending', 'sent', 'failed', 'not_required') DEFAULT 'not_required',
  webhook_attempts INT DEFAULT 0,
  webhook_last_attempt TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_provider_idempotency (provider_id, idempotency_key),
  INDEX idx_pt_provider (provider_id),
  INDEX idx_pt_provider_code (provider_code),
  INDEX idx_pt_status (status),
  INDEX idx_pt_cust (cust_id),
  INDEX idx_pt_created (created_at),
  INDEX idx_pt_webhook (webhook_status),
  INDEX idx_pt_txcode (transaction_code),
  CONSTRAINT fk_pt_provider FOREIGN KEY (provider_id) REFERENCES api_providers(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
